[package]
name = "raylib_game"
version = "0.1.0"
edition = "2021"

[dependencies]
imgui = "0.12.0"
raylib = {version = "5.0.2" }
raylib_imgui_rs = "0.2.0"
box2d-rs = "0.0.4"

[profile.dev.build-override]
debug = true
